import type { Metadata } from 'next'
import { Inter, Inter_Tight, Familjen_Grotesk } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })
const inter_tight = Inter_Tight({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='pt-BR'>
      <body className={clsx(
        inter.className,
        inter_tight.className,
        'bg-[#14151D]'
      )}>{children}</body>
    </html>
  )
}
